spring:
    datasource:
        dbcp2:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/database_test?useTimezone=true&serverTimezone=UTC
            username: root
            password: vick1771
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
            show-sql: false